name: link_memo_holder
description: link and memo save app.

publish_to: "none"

version: 1.2.1+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.3
  awesome_dialog: ^2.2.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.0
  animated_bottom_navigation_bar: ^0.3.2
  receive_sharing_intent: ^1.4.5
  flutter_easyloading: ^3.0.3
  http: ^0.13.4
  metadata_fetch: ^0.4.1
  flutter_spinkit: "^5.1.0"
  intl: ^0.17.0
  flutter_local_notifications: ^9.5.2
  flutter_native_timezone: ^2.0.0
  date_time_picker: "^2.1.0"
  google_mobile_ads: ^1.2.0
  flutter_native_splash: ^2.1.3+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: "assets/icons/splash.png"
  color: "D5F6FC"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
